### ISSUE TITLE
README incorrectly claims you ported Detail Daemon to ComfyUI

### ISSUE THREAD

**Issue by blepping** [tatookan/comfuinoda-Navyblue#1]
your README reads:

> I looked at the Detail Daemon for Auto1111/Forge and tried porting it to Comfui and got remarkable results!

you appear to be claiming (or at least very strongly implying) you ported Detail Daemon to ComfyUI, however what you're publishing is just a modified version of my original Lying Sigma Sampler node: https://gist.github.com/blepping/50103df387945b3fb2691a46812b4a64

you should update your README to attribute the sources you based your changes on. this is an example of how to do it correctly: https://github.com/Jonseed/ComfyUI-Detail-Daemon#credits

you are absolutely welcome to use my code as long as you don't claim _you_ made it. ideally you'd also credit me for the original version you're basing your changes on, even a comment in the source would be reasonable.

**Comment by tatookan** [comment]
@blepping As my first github repository I haven't done enough, thanks for your guidance and advice and for allowing me to learn from your work, I'm going to do that!

**Comment by blepping** [comment]
thanks! appreciate it.

you're actually crediting more than you need to now. :) i was just saying the way ComfyUI Detail Daemon handled it was good, not that you needed to do the exact same thing. you're not using my interpolation stuff (yet, anyway) or the schedule generation stuff from the original Detail Daemon - just the concept.

anyway, that part isn't a complaint or anything. people usually aren't going to get mad about being overly credited! up to you if you want to change it and possibly you have plans to use those parts in the future.

good luck with your project!
